---
# file: create_cluster.yml
- hosts: assisted_service
  connection: local
  gather_facts: True
  roles:
    - create_cluster
    - generate_iso
  vars:
    - create: False
    - secure: False
    - generate: False
    - download: False
    - upload: True
    - CLUSTER_NAME: "test"
    - BASE_DNS_DOMAIN: "ran.local"
    - ASSISTED_INSTALL_HOST: "10.198.6.70"
    - ASSISTED_INSTALL_PORT: 8090
    - HTTP_STORE_HOST: "10.198.6.70"
    - HTTP_STORE_PORT: 8877
    - CLUSTER_ID: ce8537df-7ce5-491a-a811-939095d49e07
