
- name: get token
  hosts: bastion
  gather_facts: True
  
  roles:
    - sonofspike.ocm.get_token
  vars:
   - token_epoch: "{{ token_epoch }}"
 
- name: Monitoring hosts installation
  hosts: masters, workers, bastion_token
  gather_facts: True
  strategy: free
  roles:
    - { role: sonofspike.ocm.manage_token, when: "'manage_token' in group_names" }
    - role: monitor_host
  vars:
    - access_token: "{{ hostvars['bastion_token']['access_token'] }}"

    - debug: True
    - ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] }}"
    - ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] }}"
    - CLUSTER_ID: "{{ cluster_id }}"

# TODO: once completed grap cluster credentials
- name: Monitoring cluster installation
  hosts: bastion
  gather_facts: False
  roles:
    - monitor_cluster
  vars:
    - debug: True
    - ASSISTED_INSTALLER_HOST: "{{ hostvars['assisted_installer']['host'] }}"
    - ASSISTED_INSTALLER_PORT: "{{ hostvars['assisted_installer']['port'] }}"
    - CLUSTER_ID: "{{ cluster_id }}"

- name: release access token
  hosts: bastion
  tasks:
  - name: release access_token
    include_role:
      name: sonofspike.ocm.release_token
    