---
# file: install_cluster.yml
- hosts: kaloom-infra
  roles:
    - install_cluster
  vars:
    - install: True
    - debug: True
    - ASSISTED_INSTALLER_HOST: "10.198.6.70"
    - ASSISTED_INSTALLER_PORT: 8090
    - CLUSTER_ID: "{{ cluster_id }}"
    - INGRESS_VIP: "{{ ingress_vip }}"
    - API_VIP: "{{ api_vip }}"
    - VIP_DHCP_ALLOCATION: "{{ vip_dhcp_allocation }}"
