---
 
- name: install cluster
  block:
  - name: install cluster from cluster.yml
    include_tasks: cluster.yml
  #rescue:

#   - import_role:
#       name: sonofspike.ocm.get_token
#   - import_role:
#      name: sonofspike.ocm.refresh_token