---
- name: Mount Live ISO, Boot into Live ISO (Lenovo servers)
  block:
    - name: Lenovo Power On the System
      community.general.redfish_command:
        category: Systems
        command: PowerOn
        baseuri: "{{ hostvars[item]['bmc_address'] }}"
        username: "{{ hostvars[item]['bmc_user'] }}"
        password: "{{ hostvars[item]['bmc_password'] }}"
      register: redfish_reply

    - debug:
        var: redfish_reply

    - name: Lenovo Eject Virtual Media
      uri:
        url: "https://{{ hostvars[item]['bmc_address'] }}/redfish/v1/Managers/1/VirtualMedia/EXT1"
        user: "{{ hostvars[item]['bmc_user'] }}"
        password: "{{ hostvars[item]['bmc_password'] }}"
        method: PATCH
        body_format: json
        body: {"Image": null, "Inserted": false}
        status_code: [200, 204]
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
      register: redfish_reply

    - debug:
        var: redfish_reply

    - name: Lenovo Insert Virtual Media
      uri:
        url: "https://{{ hostvars[item]['bmc_address'] }}/redfish/v1/Managers/1/VirtualMedia/EXT1"
        user: "{{ hostvars[item]['bmc_user'] }}"
        password: "{{ hostvars[item]['bmc_password'] }}"
        method: PATCH
        body_format: json
        body: {"Image":"{{ boot_iso }}", "Inserted": true}
        status_code: [200, 204]
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
      register: redfish_reply

    - debug:
        var: redfish_reply
#      when: debug|bool == True

    - name: Lenovo Set Boot Once from Virtual Media
      uri:
        url: "https://{{ hostvars[item]['bmc_address'] }}/redfish/v1/Systems/1"
        user: "{{ hostvars[item]['bmc_user'] }}"
        password: "{{ hostvars[item]['bmc_password'] }}"
        method: PATCH
        body_format: json
        body: {
        "Boot": {
            "BootSourceOverrideEnabled": "Once",
            "BootSourceOverrideMode": "UEFI",
            "UefiTargetBootSourceOverride": "EXT1",
            "BootSourceOverrideTarget": "UefiTarget"
            }
        }
        status_code: [200, 204]
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
      register: redfish_reply

    - debug:
        var: redfish_reply
#      when: debug|bool == True

    - name: Lenovo Restart the System
      uri:
        url: "https://{{ hostvars[item]['bmc_address'] }}/redfish/v1/Systems/1/Actions/ComputerSystem.Reset"
        user: "{{ hostvars[item]['bmc_user'] }}"
        password: "{{ hostvars[item]['bmc_password'] }}"
        method: POST
        body_format: json
        body: '{"ResetType": "ForceRestart"}'
        status_code: [200, 204]
        force_basic_auth: yes
        validate_certs: no
        return_content: yes
      register: redfish_reply

    - debug:
        var: redfish_reply
#      when: debug|bool == True
